### ISSUE TITLE
Create binary of gauntlt that can be downloaded and run without using gem install

### ISSUE THREAD

**Issue by bowsersenior** [gauntlt/gauntlt#45]
@jeremiahshirk had the brilliant idea to compile gauntlt into a jar file using JRuyb that could be downloaded without having to install anything. We could also create a mac binary using MacRuby (since many of our potential users will be on OS X).

This makes a lot of sense and would speed up the adoption of gauntlt.

**Comment by apolloclark** [comment]
@wickett is going to solve this with a Go rewrite here: https://github.com/gauntlt/gauntlt-go
