### ISSUE TITLE
sqlmap seems to be broken and freezes when running

### ISSUE THREAD

**Issue by wickett** [gauntlt/gauntlt#73]
Just running a simple sqlmap attack causes gauntlt to lock up.  Not sure if something changed with sqlmap or what...

@jeremiahshirk can you help test this out?  I moved features/attacks/sqlmap.attack to .broken for now so that it is skipped in the CI.

**Comment by apolloclark** [comment]
Fixed in latest version with update to a newer sqlmap version.
