### ISSUE TITLE
gaunlt not able to replace profile variable 

### ISSUE THREAD

**Issue by Gaurang033** [gauntlt/gauntlt#83]
Hi Guys, 

I was trying to generate the arachni html report using gauntlt, however it seems like gauntlt is not able to replace the profile variable. 

following is the code I am using. 
Feature: Run Basic Security Test on Application

  Background:
    Given The default aruba timeout is 600 seconds

```
And the following profile:
  | name | value|
  | LIB | /root/gauntlt/ |
  | REPORT | /root/gauntlt/report/ |
  | ARACHNI_HTML_REPORT | /var/www/html/arachni_report/ |
```

Scenario: generate HTML report for Arachni
  Given The default aruba timeout is 600 seconds
  When I run `arachni_reporter <REPORT>arachni_login.afr --reporter=html:outfile=<REPORT>arachni_login_report.html.zip`
  And  I run `unzip -o <REPORT>arachni_login_report.html.zip -d <ARACHNI_HTML_REPORT>`
  Then the output should contain "arachni_login.ar"
  And a file named "<ARACHNI_HTML_REPORT>index.html" should exist

And following is the error I am getting. 

 And I run `unzip -o <REPORT>arachni_login_report.html.zip -d <ARACHNI_HTML_REPORT>`                                   # aruba-0.5.4/lib/aruba/cucumber.rb:84
    Then the output should contain "arachni_login.ar"                                                                     # aruba-0.5.4/lib/aruba/cucumber.rb:131
      expected "Arachni - Web Application Security Scanner Framework v1.1\n   Author: Tasos \"Zapotek\" Laskos tasos.laskos@arachni-scanner.com\n\n           (With the support of the community and the Arachni Team.)\n\n   Website:       http://arachni-scanner.com\n   Documentation: http://arachni-scanner.com/wiki\n\n\n[-] Report does not exist: /root/gauntlt/BAT_Security/tmp/aruba/<REPORT>arachni_login.afr\nunzip:  cannot find or open <REPORT>arachni_login_report.html.zip, <REPORT>arachni_login_report.html.zip.zip or <REPORT>arachni_login_report.html.zip.ZIP.\n" to include "arachni_login.ar"
      Diff:
      @@ -1,2 +1,12 @@
      -arachni_login.ar
      +Arachni - Web Application Security Scanner Framework v1.1
      +   Author: Tasos "Zapotek" Laskos tasos.laskos@arachni-scanner.com
      +
      +           (With the support of the community and the Arachni Team.)
      +
      +   Website:       http://arachni-scanner.com
      +   Documentation: http://arachni-scanner.com/wiki
      +
      +
      +[-] Report does not exist: /root/gauntlt/BAT_Security/tmp/aruba/<REPORT>arachni_login.afr
      +unzip:  cannot find or open <REPORT>arachni_login_report.html.zip, <REPORT>arachni_login_report.html.zip.zip or <REPORT>arachni_login_report.html.zip.ZIP.
       (RSpec::Expectations::ExpectationNotMetError)
      generate_report.attack:16:in `Then the output should contain "arachni_login.ar"'
    And a file named "<ARACHNI_HTML_REPORT>index.html" should exist                                                       # aruba-0.5.4/lib/aruba/cucumber.rb:298

Failing Scenarios:
cucumber generate_report.attack:12 # Scenario: generate HTML report for Arachni

**Comment by wickett** [comment]
still a problem?  I think this was fixed a while back and documented in the wiki. Please reopen if not.
