### ISSUE TITLE
Typhoeus 0.3.3 on which arachni 0.4.6 relies does not successfully install thus making bundle install fail

### ISSUE THREAD

**Issue by cgotcu** [gauntlt/gauntlt#91]
Modify the arachni version to 1.0.6 from 0.4.6 and bundle install completes correctly. That is the most recent version of arachni that supports Ruby 1.9.3.

Note that since arachni needs nokogiri version 1.6.2.1 you have to change that in the gemspec.

**Comment by apolloclark** [comment]
Fixed with the latest version
