### ISSUE TITLE
Release new gem for Gauntlt

### ISSUE THREAD

**Issue by wickett** [gauntlt/gauntlt#93]
@cgotcu and @apolloclark 

Are we ready to release a new gem?  Seems good to me, but wanted to make sure you were good with it.

**Comment by apolloclark** [comment]
I'm happy with it on Kali Linux 2.0, Debian Jessie, Ubuntu 14.04, and Ubuntu 15.10; haven't tested it on Mac.

**Comment by cgotcu** [comment]
Looks good to me. I can test on latest MacOS.
Can we wait one more day? I have a couple more small additions (output file and a couple more things I think .. need to do a diff as I'm working on a few more things)

**Comment by wickett** [comment]
@cgotcu sounds good!

I just replied to #94 with yes, this weekend.  Should have read this first :smile: 

Thanks for testing on the latest OS X.  I have yet to update to it, maybe this weekend!

**Comment by cgotcu** [comment]
No worries! :)
I just did a pull request with a tiny change but that should be it for
another couple of weeks. I asked in a comment about support of 1.9. Is
there value to that?

**Comment by wickett** [comment]
This is old, we released a new gem a while back.
