### ISSUE TITLE
Gauntlt Slack Channel

### ISSUE THREAD

**Issue by wickett** [gauntlt/gauntlt#95]
So google groups and IRC are the 'official' channels for the gauntlt community.  Most are really quiet and not really used.

I propose we nuke IRC and create a slack channel for gauntlt.  Since the current community model seems to be broken or at least overly quiet, I am thinking this might help us out.  We can still use email for release blasts and the like.

Anyone against this idea?

@apolloclark @karthequian @jeremiahshirk @cgotcu @boldersecurity @gauntlt/gauntlt-friends @gauntlt/gauntlt-contributors

**Comment by apolloclark** [comment]
I haven't used IRC actively since 2004. Google Groups never took off. I still don't have a reliable way of learning about new releases for most of my open-source tools. Twitter announcements, with an accompanying blog post, preferably a short Youtube video, seems to work well. Slack sounds good.

**Comment by schatekar** [comment]
I participate in gitter chats of lot of open source projects. That works quite well as you can reference code and issues from github directly from the chat.

**Comment by wickett** [comment]
@schatekar that sounds pretty good too but went ahead and made a slack channel for now.  We will give that a try.

If you want to join, hit me up at `james+++++@+++++gauntlt.org`  (remove the `+`) with your email addy if you want to join.

We can get that auto-slack joiner thing setup soon... Or maybe some other process.

**Comment by karthequian** [comment]
I like slack. Let's do it.

**Comment by mtesauro** [comment]
I am good with Slack.  Add me when you get a chance.

--
-- Matt Tesauro
OWASP AppSec Pipeline Lead
https://www.owasp.org/index.php/OWASP_AppSec_Pipeline
OWASP WTE Project Lead
https://www.owasp.org/index.php/OWASP_Web_Testing_Environment_Project
http://AppSecLive.org - Community and Download site

**Comment by cgotcu** [comment]
Sounds great.. I was on IRC the other day talking to myself :)
Please add me as well.

**Comment by pmbenjamin** [comment]
Is this slack channel open to the community or just for Gauntlt dev contributors?

**Comment by karthequian** [comment]
@pmbenjamin we have different rooms for different things so feel free to join us! https://gauntlt.slack.com

**Comment by pmbenjamin** [comment]
@karthequian I believe I need to be invited petermbenjamin [at] gmail [dot] com

**Comment by karthequian** [comment]
@pmbenjamin sent you an invite. If anyone else wants an invite feel free to ping us here. @cgotcu I didn't find an email address for you linked to your github account; update this thread with one and I'll add you as well!

**Comment by Joeyn414** [comment]
@karthequian  can you please add me as well. Thank you.

**Comment by infosecrepo** [comment]
Is there a way to self-register to the Gauntlt Slack group? Alternatively, who is the best to hit up for an invite? Thanks!

**Comment by wickett** [comment]
http://bit.ly/2EU9yGh

Try that link, looking forward to seeing you there!
