### ISSUE TITLE
Is it possible to extend gauntlt with custom steps

### ISSUE THREAD

**Issue by aisbaa** [gauntlt/gauntlt#97]
I would like extend step library to be able to use "browser" in audit scenarios.

```Cucumber
Feature: Confidentiality breach

  Background:
    Given I'am logged in as customer "31"

  Scenario: Expose other customer data
    When I navigate to "/customer/52"
    Then customer "52" information is visible
```

**Comment by apolloclark** [comment]
Yes, to add custom steps, the easiest way is to reuse the Generic Attack Adapter:

- Background, Given definitions are in: /lib/gauntlt/attack_adapters/generic.rb
    - using regex, attempt to match a string partial, call a function
    - easiest way is to reuse the function "run_with_profile", located in: /lib/gauntlt/attack_adapters/support/profile_helper.rb

Your specific attack will involve sending HTTP requests, and doing an assertion on the return. You could use:
curl
python lettuce
ruby capybara
selenium
jq
etc.

Essentially, with the "Generic Attack Adapter," you're using GWT (Given / When / Then) syntax as a wrapper around a raw command line call. This makes it very easy to write attacks using tools that Gauntlt doesn't specifically support yet.

After you've written up 10+ attack steps, and want to have more convenience functions, like attack alias, definitely try writing up a customer attack adapter, similar to how sqlmap adapter was written.

Fork this repo, write some custom attack steps, and let me know after you have a working example. I'll review it, and give you some tips, advice, etc. on it. I personally like to use Gauntlt, running on Kali Linux VM in Virtualbox. It has a ton of pen-testing tools pre-installed.

**Comment by aisbaa** [comment]
Cheers mate, thanks for the tips :+1:

**Comment by apolloclark** [comment]
Glad to help! Let me know how it goes.

**Comment by karthequian** [comment]
Closing this issue because it seems to have been answered.
