### ISSUE TITLE
Is there development still going on for this project?

### ISSUE THREAD

**Issue by PimmyTrousers** [gauntlt/gauntlt#99]
Same as above, I was just curious whether there was development going on for this project still as I am very interested in contributing.

**Comment by apolloclark** [comment]
Yes, it is still in development.

Speaking only for myself... It's an open-source project, contributors have full-time jobs, so it's more of a weekend project. I contribute when there is spare time outside of my 40+ hrs. / week job. Personally, I'm working on making a demo with Gauntlt, on Kali Linux, against @karthequian Gruyere Docker containerhttps://hub.docker.com/r/karthequian/gruyere/ tied into the new Jenkins 2.0 Pipeline plugin https://github.com/apolloclark/vagrant-jenkins-pipeline as a demo of "Automated Security Scanning as Unit Tests in a Continuous Integration environment."

**Comment by PimmyTrousers** [comment]
I am very interested in seeing a demo against the Gruyere container.

**Comment by apolloclark** [comment]
Awesome, I'll be working on it more this week, hopefully have something by Fri. :)

**Comment by PimmyTrousers** [comment]
Awesome!

**Comment by karthequian** [comment]
Hi @PimmyTrousers! Development is still going on for gauntlt, but we're not being as aggressive as we were before. @wickett and I have been dabbling a rewrite of gauntlt in go, but it's still very much a work in progress.

**Comment by schatekar** [comment]
@karthequian Out of curiosity - why you prefer Go over anything else?

**Comment by AARonSTeneo** [comment]
It would be great to see more of what the community has done with Gauntlt and how everyone is using it. I know we have done some interesting things that others would probably find useful as well. Actually I run into folks all the time that are finding new ways to add on or use Gauntlt in interesting ways. I wonder what would be the best ways to gather/share that info.

**Comment by wickett** [comment]
I think a good way to share about gauntlt, is to get the slack group going and get the conversation rolling. #95

**Comment by wickett** [comment]
alright join us in slack > http://bit.ly/2EU9yGh
